"""create seed

Revision ID: 42926826b376
Revises: 71c68f233f42
Create Date: 2023-08-07 14:41:35.629937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42926826b376'
down_revision = '71c68f233f42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
