"""updates seed

Revision ID: 595c4ef42041
Revises: b1f8203fe609
Create Date: 2023-08-07 22:30:29.516700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '595c4ef42041'
down_revision = 'b1f8203fe609'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
