"""modifies dev

Revision ID: b1f8203fe609
Revises: 0aef27113b29
Create Date: 2023-08-07 15:19:39.694027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1f8203fe609'
down_revision = '0aef27113b29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
